---
version: 2.1

orbs:
  release-management: salesforce/npm-release-management@4

workflows:
  test-and-release:
    jobs:
      - release-management/validate-pr:
          filters:
            branches:
              ignore: main
      - release-management/test-package:
          name: node-14
          node_version: node-14
          os: linux
      - release-management/test-package:
          name: win-node-14
          node_version: node-14
          os: windows
      - release-management/release-package:
          filters:
            branches:
              only: main
          requires:
            - node-latest

  dependabot-automerge:
    triggers:
      - schedule:
          cron: "0 2,5,8,11 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - release-management/dependabot-automerge
